name: Deploy to EC2

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
 
- name: Debug SSH Setup
  run: |
    mkdir -p ~/.ssh
    printf "%s" "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ls -la ~/.ssh/
    cat ~/.ssh/id_rsa | head -n 5
    ssh-keyscan -H ${{ secrets.EC2_HOST }} || echo "Failed to scan keys"



      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /path/to/EPAprep  # Update this path if needed
            git pull origin main
            sudo systemctl restart your-app-service  # Replace with your app service if applicable
          EOF
